#!/usr/bin/env bash
set -euo pipefail

target="$HOME/.config/hatori/hatori.env"
mkdir -p "$(dirname "$target")"
if [ ! -f "$target" ]; then
  token="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
)"
  cat > "$target" <<ENV
HATORI_API_TOKEN=${token}
UI_PORT=23571
API_PORT=23572
HATORI_GENERATOR_ORDER=mlx,ollama
HATORI_OLLAMA_MODEL=llama3.2:3b
HATORI_MLX_MODEL=
HATORI_SKIP_OLLAMA_ENSURE=0

# Per-task routing (final structure)
HATORI_ROUTE_REPLY_WRITE_BACKEND=mlx
HATORI_ROUTE_REPLY_WRITE_MODEL=
HATORI_ROUTE_REPLY_WRITE_FALLBACK_BACKEND=ollama
HATORI_ROUTE_REPLY_WRITE_FALLBACK_MODEL=gemma2:2b

HATORI_ROUTE_PLAN_WRITE_BACKEND=mlx
HATORI_ROUTE_PLAN_WRITE_MODEL=
HATORI_ROUTE_PLAN_WRITE_FALLBACK_BACKEND=ollama
HATORI_ROUTE_PLAN_WRITE_FALLBACK_MODEL=gemma2:2b

HATORI_ROUTE_REWRITE_POLISH_BACKEND=mlx
HATORI_ROUTE_REWRITE_POLISH_MODEL=
HATORI_ROUTE_REWRITE_POLISH_FALLBACK_BACKEND=ollama
HATORI_ROUTE_REWRITE_POLISH_FALLBACK_MODEL=gemma2:2b

HATORI_ROUTE_CLASSIFY_INTENT_BACKEND=ollama
HATORI_ROUTE_CLASSIFY_INTENT_MODEL=gemma3:1b
HATORI_ROUTE_CLASSIFY_INTENT_FALLBACK_BACKEND=ollama
HATORI_ROUTE_CLASSIFY_INTENT_FALLBACK_MODEL=llama3.2:1b

HATORI_ROUTE_EXTRACT_FIELDS_BACKEND=ollama
HATORI_ROUTE_EXTRACT_FIELDS_MODEL=gemma3:1b
HATORI_ROUTE_EXTRACT_FIELDS_FALLBACK_BACKEND=ollama
HATORI_ROUTE_EXTRACT_FIELDS_FALLBACK_MODEL=llama3.2:1b

HATORI_ROUTE_CONTEXT_PACK_BACKEND=ollama
HATORI_ROUTE_CONTEXT_PACK_MODEL=gemma3:1b
HATORI_ROUTE_CONTEXT_PACK_FALLBACK_BACKEND=ollama
HATORI_ROUTE_CONTEXT_PACK_FALLBACK_MODEL=llama3.2:1b

HATORI_ROUTE_RETRIEVAL_QUERY_BUILD_BACKEND=ollama
HATORI_ROUTE_RETRIEVAL_QUERY_BUILD_MODEL=gemma3:1b
HATORI_ROUTE_RETRIEVAL_QUERY_BUILD_FALLBACK_BACKEND=ollama
HATORI_ROUTE_RETRIEVAL_QUERY_BUILD_FALLBACK_MODEL=llama3.2:1b

HATORI_ROUTE_EDIT_PATTERN_CLUSTER_BACKEND=ollama
HATORI_ROUTE_EDIT_PATTERN_CLUSTER_MODEL=gemma3:1b
HATORI_ROUTE_EDIT_PATTERN_CLUSTER_FALLBACK_BACKEND=ollama
HATORI_ROUTE_EDIT_PATTERN_CLUSTER_FALLBACK_MODEL=llama3.2:1b

HATORI_ROUTE_ANSWER_SCORE_BACKEND=ollama
HATORI_ROUTE_ANSWER_SCORE_MODEL=llama3.2:3b
HATORI_ROUTE_ANSWER_SCORE_FALLBACK_BACKEND=ollama
HATORI_ROUTE_ANSWER_SCORE_FALLBACK_MODEL=gemma2:2b

HATORI_ROUTE_QUALITY_GATE_BACKEND=ollama
HATORI_ROUTE_QUALITY_GATE_MODEL=llama3.2:3b
HATORI_ROUTE_QUALITY_GATE_FALLBACK_BACKEND=ollama
HATORI_ROUTE_QUALITY_GATE_FALLBACK_MODEL=gemma2:2b
ENV
  chmod 600 "$target"
  echo "Created $target"
else
  chmod 600 "$target"
  echo "Exists $target"
fi

echo "Next steps:"
echo "- Edit $target and set HATORI_MLX_MODEL + writer route model for Apertus."
echo "- Run bootstrap: make bootstrap"
echo "- Token value is stored in $target (not printed)."
